version: '2'
services:
  dev:
    container_name: dev
    environment:
      - DISPLAY=${DISPLAY}
    image: merlinnot/devver
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "14500:14500"
    volumes:
      - .:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
